In [1]:
import numpy as np
#import PyKDL as kdl
import math
from typing import Tuple


In [32]:

def rotate(P_B: np.ndarray) -> np.ndarray:
  """Rotate a given vector by a set value

  Args:
      P_B (np.ndarray): Position Vector

  Returns:
      np.ndarray: rotated array 
  """  
  P_B = P_B.reshape(3, 1)
  th_y = np.pi / 2
  th_z = np.pi / 4

  R_Y = np.array([[np.cos(th_y), 0, np.sin(th_y)],
                    [0, 1, 0],
                    [-np.sin(th_y), 0, np.cos(th_y)]
    ])
  
  R_Z = np.array([[np.cos(th_z), -np.sin(th_z), 0],
                    [np.sin(th_z), np.cos(th_z), 0],
                    [0, 0, 1]
    ])
  
  A_R_B = R_Y @ R_Z
  P_A = A_R_B @ P_B
  
  return P_A

In [33]:
print(rotate(np.array([1, 0, 0])))
print(np.array([[1], [0], [0]]))

[[ 4.32978028e-17]
 [ 7.07106781e-01]
 [-7.07106781e-01]]
[[1]
 [0]
 [0]]


In [3]:
import numpy as np

B_F = np.array([[1,7,3]]).transpose()

# Rotation of A wrt B is given from the trasformation of A wrt B
B_R_A = np.array([[np.cos(np.pi/4), -np.sin(np.pi/4), 0],
                  [np.sin(np.pi/4), np.cos(np.pi/4), 0],
                  [0, 0, 1]])

# Transpose to get rotation of B wrt A
A_R_B = B_R_A.transpose()

# Now we can compute the coordinates of point F in frame A
A_F = A_R_B @ B_F

print(A_F)

[[5.65685425]
 [4.24264069]
 [3.        ]]


In [6]:
A_T_B = np.eye(4)
A_T_B[0:3, 0:3] = np.array([[1,0,0],
                                 [0,1,0],
                                 [0,0,1]])  
A_T_B[:3, 3] = np.array([1,2,3]).T
print(A_T_B)

x = np.array([4,5,6,1]).reshape(4)
print(x)

[[1. 0. 0. 1.]
 [0. 1. 0. 2.]
 [0. 0. 1. 3.]
 [0. 0. 0. 1.]]
[4 5 6 1]
